name: ttc-docker
root: <%= ENV["PWD"] %>

on_project_start:
  # Rebuild images to ensure they reflect current code
  - docker compose build prover-server monitor-server
  - docker compose up -d postgres ethereum-node

windows:
  - eth_pg_logs:
      layout: even-vertical
      panes:
        - docker compose logs -f ethereum-node
        - docker compose logs -f postgres
  - servers:
      layout: even-vertical
      panes:
        - docker compose up prover-server
        - docker compose up monitor-server
  - system:
      panes:
        - htop
  - shell:
      panes:
        - # empty shell

# Enable mouse mode
tmux_options: "-2"

# Set default shell options
tmux_command: "TERM=screen-256color tmux"

# Additional tmux configuration
pre_window: tmux set -g mouse on
tmux_attach: false
