[package]
name = "ttc"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
petgraph = { version = "0.7.1", default-features = false }
thiserror = "1.0"

[dev-dependencies]
proptest = "1.6.0"