[workspace]
resolver = "3"
members = [
    "ttc", "contract",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0"
futures = "0.3"
itertools = "0.14.0"
petgraph = { version = "0.7.1", default-features = false }
proptest = "1.6.0"
thiserror = "2.0"
tokio = { version = "1.35", features = ["full"] }
url = { version = "2.5" }

risc0-steel = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.4.0-rc.1", features = ["unstable-verifier"] }
# risc0-build-ethereum = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.4.0-rc.1" }
# risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.4.0-rc.1" }

ttc = { path = "ttc" }
ttc-contract = { path = "ttc-contract" }