version: '3.8'

services:
  ethereum-node:
    image: ${ETHEREUM_NODE_IMAGE:-}
    build:
      context: ./docker/anvil
      dockerfile: Dockerfile
    ports:
      - "${ETH_PORT:-8545}:8545"
    environment:
      - CHAIN_ID=${CHAIN_ID:-31337}
      - ACCOUNTS=${ACCOUNTS:-10}
      - BALANCE=${BALANCE:-100000}
    command: >
      anvil
      --host 0.0.0.0
      --port 8545
      --chain-id ${CHAIN_ID:-31337}
      --accounts ${ACCOUNTS:-10}
      --balance ${BALANCE:-100000}
      
  prover-server:
    image: ${PROVER_SERVER_IMAGE:-}
    build:
      context: .
      dockerfile: docker/prover-server/Dockerfile
    ports:
      - "${PROVER_PORT:-8546}:8546"
    depends_on:
      - ethereum-node
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - RISC0_DEV_MODE=${RISC0_DEV_MODE:-true}
    command: >
      sh -c "/app/target/release/prover-server 
      --node-url http://ethereum-node:${ETH_PORT:-8545} 
      --json-rpc-port ${PROVER_PORT:-8546}"