[package]
name = "host"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
proptest.workspace = true
risc0-steel.workspace = true
ttc = { workspace = true, features = ["test"] }
contract.workspace = true
tokio.workspace = true
url.workspace = true
