[package]
name = "prover-common"
version.workspace = true
edition.workspace = true

[dependencies]

futures.workspace = true
jsonrpsee = { workspace = true, features = ["client", "macros", "server"] }
serde.workspace = true

risc0-steel = { workspace = true, features = ["host"]}