[package]
name = "ttc"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
petgraph = { version = "0.7.1", default-features = false }
proptest = "1.6.0"
thiserror = "1.0"

[dev-dependencies]
itertools = "0.14.0"

[features]
test = []