[package]
name = "monitor-common"
version.workspace = true
edition.workspace = true

[dependencies]
alloy.workspace = true
futures.workspace = true
hex.workspace = true
jsonrpsee = { workspace = true, features = ["client", "macros", "server"] }
serde.workspace = true