[package]
name = "ttc-contract"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = "2.0"
serde = "1.0"
tokio = { version = "1.0", features = ["full"] }
eyre = "0.6"
rand = "0.9"
futures = "0.3"