name: Rust Tests

on:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
        
    - name: Run Tests
      run: cargo test