name: Rust Tests

on:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    # Install Foundry
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    # Build contracts
    - name: Build contracts
      working-directory: ./ttc-contract
      run: forge build
        
    - name: Run Tests
      run: cargo test