name: Lint

on:
  pull_request:

jobs:
  lint:
    name: Run Lints
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4    

    - uses: Swatinem/rust-cache@v2        

    # Install Foundry
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install RISC0
      uses: ./.github/actions/install-risc0
      with:
        version: 1.2.4


    # Build contracts
    - name: Build contracts
      run: | 
        make build-methods
        make compile-contracts

    - name: Check formatting
      run: cargo fmt --check

    - name: Run clippy
      run: make lint