name: Node Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day

jobs:
  node_tests:
    name: Run Node Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install RISC0
      uses: ./.github/actions/install-risc0
      with:
        version: 1.2.4
    
    # Login to DockerHub with access token
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    # Set up Docker Buildx for better caching
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Try to pull cache images (with separate tags for cache)
    - name: Pull cache images
      continue-on-error: true  # Continue even if images don't exist yet
      run: |
        docker pull elladic/ttc-prover-server:cache || true
        docker pull elladic/anvil-node:cache || true
    
    # Build with cache from pulled images
    - name: Build Docker images
      run: |
        COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
        docker compose build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from elladic/ttc-prover-server:cache \
          --cache-from elladic/anvil-node:cache
    
    # Run mock tests for regular pushes/PRs
    - name: Run node tests with mocks
      if: github.event_name != 'schedule'
      run: |
        RISC0_DEV_MODE=true docker compose up -d
        sleep 5  # Wait for services to start
        make run-node-tests-mock
    
    # Run full tests for nightly builds
    - name: Run full node tests
      if: github.event_name == 'schedule'
      run: |
        RISC0_DEV_MODE=false docker compose up -d
        sleep 5  # Wait for services to start
        make run-node-tests
    
    # Get short git SHA for tagging
    - name: Get short SHA
      id: short_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    # Push versioned and cache images
    - name: Push images
      if: github.ref == 'refs/heads/main' && (success() || failure())
      continue-on-error: true
      run: |
        # Get image IDs
        PROVER_IMAGE_ID=$(docker compose images -q prover-server)
        ETH_NODE_IMAGE_ID=$(docker compose images -q ethereum-node)
        
        # Only push if images were successfully built
        if [ ! -z "$PROVER_IMAGE_ID" ]; then
          # Tag with git SHA for versioning
          docker tag $PROVER_IMAGE_ID elladic/ttc-prover-server:${{ steps.short_sha.outputs.sha }}
          docker push elladic/ttc-prover-server:${{ steps.short_sha.outputs.sha }}
          
          # Tag as cache for future builds
          docker tag $PROVER_IMAGE_ID elladic/ttc-prover-server:cache
          docker push elladic/ttc-prover-server:cache
        fi
        
        if [ ! -z "$ETH_NODE_IMAGE_ID" ]; then
          # Tag with git SHA for versioning
          docker tag $ETH_NODE_IMAGE_ID elladic/anvil-node:${{ steps.short_sha.outputs.sha }}
          docker push elladic/anvil-node:${{ steps.short_sha.outputs.sha }}
          
          # Tag as cache for future builds
          docker tag $ETH_NODE_IMAGE_ID elladic/anvil-node:cache
          docker push elladic/anvil-node:cache
        fi
    
    # Push latest tag only on successful builds from main branch
    - name: Push latest tag
      if: github.ref == 'refs/heads/main' && success()
      run: |
        PROVER_IMAGE_ID=$(docker compose images -q prover-server)
        ETH_NODE_IMAGE_ID=$(docker compose images -q ethereum-node)
        
        # Tag and push latest versions
        docker tag $PROVER_IMAGE_ID elladic/ttc-prover-server:latest
        docker push elladic/ttc-prover-server:latest
        
        docker tag $ETH_NODE_IMAGE_ID elladic/anvil-node:latest
        docker push elladic/anvil-node:latest
    
    # Cleanup
    - name: Cleanup
      if: always()
      run: docker compose down